USE [master]
GO

/****** Object:  Database [victor_BD_testes_post]    Script Date: 11/09/2019 12:02:21 ******/
CREATE DATABASE [victor_BD_testes_post]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'victor_BD_testes_post', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.I2KBATATA\MSSQL\DATA\victor_BD_testes_post.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'victor_BD_testes_post_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.I2KBATATA\MSSQL\DATA\victor_BD_testes_post_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [victor_BD_testes_post].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [victor_BD_testes_post] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET ARITHABORT OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [victor_BD_testes_post] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [victor_BD_testes_post] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET  DISABLE_BROKER 
GO

ALTER DATABASE [victor_BD_testes_post] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [victor_BD_testes_post] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [victor_BD_testes_post] SET  MULTI_USER 
GO

ALTER DATABASE [victor_BD_testes_post] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [victor_BD_testes_post] SET DB_CHAINING OFF 
GO

ALTER DATABASE [victor_BD_testes_post] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [victor_BD_testes_post] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [victor_BD_testes_post] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [victor_BD_testes_post] SET QUERY_STORE = OFF
GO

ALTER DATABASE [victor_BD_testes_post] SET  READ_WRITE 
GO

